import { useEffect, useState } from "react";

type Metrics = {
  dataset: string;
  mae: number;
  rmse: number;
  r2: number;
  n_samples: number;
};

type FeatureImportance = {
  feature: string;
  importance: number;
};

export default function HousingModelSection() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [features, setFeatures] = useState<FeatureImportance[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadArtifacts() {
      try {
        const [metricsRes, fiRes] = await Promise.all([
          fetch("/housing-metrics.json"),
          fetch("/housing-feature-importance.json"),
        ]);

        if (!metricsRes.ok || !fiRes.ok) {
          throw new Error("Failed to load JSON artifacts");
        }

        const metricsJson = await metricsRes.json();
        const fiJson = await fiRes.json();

        setMetrics(metricsJson);
        setFeatures(fiJson);
      } catch (err) {
        console.error("Error loading housing model artifacts:", err);
      } finally {
        setLoading(false);
      }
    }

    loadArtifacts();
  }, []);

  if (loading) {
    return (
      <section
        id="housing-model"
        className="py-16 bg-slate-950 text-slate-50 flex justify-center"
      >
        <p className="text-sm text-slate-400">Loading model insights…</p>
      </section>
    );
  }

  if (!metrics) {
    return (
      <section
        id="housing-model"
        className="py-16 bg-slate-950 text-red-400 flex justify-center"
      >
        <p>Could not load housing model metrics.</p>
      </section>
    );
  }

  return (
    <section
      id="housing-model"
      className="py-16 bg-slate-950 text-slate-50"
    >
      <div className="max-w-5xl mx-auto px-4 space-y-10">
        <header className="space-y-3">
          <h2 className="text-2xl md:text-3xl font-bold">
            Housing Progression – ML Predictive Pipeline
          </h2>
          <p className="text-sm md:text-base text-slate-300 max-w-2xl">
            A Random Forest regression model trained on the scikit-learn
            housing dataset. This section reads JSON artifacts generated by
            the training script to show live metrics and feature importances.
          </p>
        </header>

        {/* Metrics cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
          <MetricCard label="MAE" value={metrics.mae} />
          <MetricCard label="RMSE" value={metrics.rmse} />
          <MetricCard label="R²" value={metrics.r2} />
          <MetricCard label="# Samples" value={metrics.n_samples} integer />
        </div>

        {/* Feature importances */}
        <div className="space-y-4">
          <h3 className="text-xl font-semibold">Top Features</h3>
          <p className="text-xs text-slate-400">
            Feature importances from the Random Forest model.
          </p>
          <div className="space-y-2">
            {features.slice(0, 10).map((f) => (
              <div key={f.feature} className="space-y-1">
                <div className="flex justify-between text-xs text-slate-400">
                  <span>{f.feature}</span>
                  <span>{f.importance.toFixed(3)}</span>
                </div>
                <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
                  <div
                    className="h-2 rounded-full bg-emerald-400"
                    style={{ width: `${(f.importance * 100).toFixed(1)}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Link to GitHub repo */}
        <div>
          <a
            href="https://github.com/diydaniel/ml-predictive-pipeline-housing"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 text-emerald-400 hover:text-emerald-300 text-sm"
          >
            <span>View training code on GitHub</span>
          </a>
        </div>
      </div>
    </section>
  );
}

type MetricCardProps = {
  label: string;
  value: number;
  integer?: boolean;
};

function MetricCard({ label, value, integer }: MetricCardProps) {
  return (
    <div className="rounded-xl bg-slate-900 border border-slate-800 p-4 flex flex-col gap-2">
      <span className="text-xs uppercase tracking-wide text-slate-400">
        {label}
      </span>
      <span className="text-2xl font-semibold">
        {integer ? value.toFixed(0) : value.toFixed(3)}
      </span>
    </div>
  );
}
